linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - misspell
    - noctx
    - bodyclose
    - prealloc
    - unconvert
    - unparam
    - whitespace
  settings:
    gofumpt:
      extra-rules: true
    misspell:
      locale: US
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
