version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - misspell
    - noctx
    - bodyclose
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofumpt:
    extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
